dist: trusty
sudo: false
language: node_js
node_js:
- '10'
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
cache:
  directories:
  - "./node_modules"
install:
- npm install
script:
- npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
after_success:
- curl -X POST -d {} https://api.netlify.com/build_hooks/${NETLIFY_WEBHOOK_KEY}?trigger_title=Travis+CI:+Success
notifications:
  slack:
    secure: KKA2LZClXh52nmkbowF+ipRfC5ufU/2ro2kGJPdBUR4NWZzbic0pq/a44t3VGGEWgz5mXEpZ4vLPX8u0VG0Ox07R+k/hckUhp+0MQqHSLQuc0cxy6RZtiIMDXnTFs/64oCqXN/r4kApSMJHHnx0wk8/TfqvwwZinF2gpe6nHBw5r5/Zbpye1viZI2DtSnjjQxaBgrM9nRcaDorvYAP7wigEW/OF3Wn8oTc+sPeuR7KCfKlowz22gSYiCmSHNg94CeFUcBkGgU1jTw3jQzESHPzZdJ8ZyYJmLHbUdYnwiOxPzymHZ9UFz5VRqVUnnrN9opILCFYgUrcVdoxOCyhnmugYPvyvCv+lUJwgbPZy6WrumqFaGCAOD9NedFrnzVnbTGsLLY5/krDaVBOMTwThawHJLICZHSEjVwwGgelSvuK3K9bqaR7w28icZ+aKx1n4euwFZbIoQ1sLpBaAIssAO9eHcHhq+iHumcde3fM93go4KlIaKIcrXJRkXA7k/DzPkMl+MV70t00WhchKFh6f+Lp/Qf/I4P6kfS5mhdeGjbxr7Uo/OkHU5sVG6JRju/5nGrxQp2n01BljzCSyaVxC21rxhPQZu1BAFpyPvN9x4E5PuorGBYAJAno94AeKf/a9h0bkGvhAlJ9QS+5zq4iC7lkJHJg5GYxSZ7uo6IxwGiXQ=
